In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("medicen.csv")
df.head(99)

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0    63    1   3     145   233    1        0       150     0      2.3    0   
1    37    1   2     130   250    0        1       187     0      3.5    0   
2    41    0   1     130   204    0        0       172     0      1.4    2   
3    56    1   1     120   236    0        1       178     0      0.8    2   
4    57    0   0     120   354    0        1       163     1      0.6    2   
..  ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
94   45    0   1     112   160    0        1       138     0      0.0    1   
95   53    1   0     142   226    0        0       111     1      0.0    2   
96   62    0   0     140   394    0        0       157     0      1.2    1   
97   52    1   0     108   233    1        1       147     0      0.1    2   
98   43    1   2     130   315    0        1       162     0      1.9    2   

    caa  thall  output  
0     0      1       1  
1     0      2       1  
2     0      2       1  
3     0      2       1  
4     0      2       1  
..  ...    ...     ...  
94    0      2       1  
95    0      3       1  
96    0      2       1  
97    3      3       1  
98    1      2       1  

[99 rows x 14 columns]

In [10]:
x = np.asarray(df[["age" , "sex" , "cp" , "trtbps" , "chol" , "fbs" , "restecg" , "thalachh" ,  "exng" , "oldpeak" , "slp" , "caa" , "thall" , "output"]])
x[0:5]

array([[ 63. ,   1. ,   3. , 145. , 233. ,   1. ,   0. , 150. ,   0. ,
          2.3,   0. ,   0. ,   1. ,   1. ],
       [ 37. ,   1. ,   2. , 130. , 250. ,   0. ,   1. , 187. ,   0. ,
          3.5,   0. ,   0. ,   2. ,   1. ],
       [ 41. ,   0. ,   1. , 130. , 204. ,   0. ,   0. , 172. ,   0. ,
          1.4,   2. ,   0. ,   2. ,   1. ],
       [ 56. ,   1. ,   1. , 120. , 236. ,   0. ,   1. , 178. ,   0. ,
          0.8,   2. ,   0. ,   2. ,   1. ],
       [ 57. ,   0. ,   0. , 120. , 354. ,   0. ,   1. , 163. ,   1. ,
          0.6,   2. ,   0. ,   2. ,   1. ]])

In [13]:
y = np.asarray(df[["output"]])
y[0:5]

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [26]:
from sklearn import preprocessing
x = preprocessing.StandardScaler().fit(x).transform(x)
x[0:5]

array([[ 0.9521966 ,  0.68100522,  1.97312292,  0.76395577, -0.25633371,
         2.394438  , -1.00583187,  0.01544279, -0.69663055,  1.08733806,
        -2.27457861, -0.71442887, -2.14887271,  0.91452919],
       [-1.91531289,  0.68100522,  1.00257707, -0.09273778,  0.07219949,
        -0.41763453,  0.89896224,  1.63347147, -0.69663055,  2.12257273,
        -2.27457861, -0.71442887, -0.51292188,  0.91452919],
       [-1.47415758, -1.46841752,  0.03203122, -0.09273778, -0.81677269,
        -0.41763453, -1.00583187,  0.97751389, -0.69663055,  0.31091206,
         0.97635214, -0.71442887, -0.51292188,  0.91452919],
       [ 0.18017482,  0.68100522,  0.03203122, -0.66386682, -0.19835726,
        -0.41763453,  0.89896224,  1.23989692, -0.69663055, -0.20670527,
         0.97635214, -0.71442887, -0.51292188,  0.91452919],
       [ 0.29046364, -1.46841752, -0.93851463, -0.66386682,  2.08204965,
        -0.41763453,  0.89896224,  0.58393935,  1.43548113, -0.37924438,
         0.97635214, -0.71

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (242, 14) (242, 1)
Test set: (61, 14) (61, 1)


In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='newton-cg').fit(X_train,y_train)
LR

C:\Users\barsam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.01, solver='newton-cg')

In [45]:
yhat = LR.predict(X_test)
yhat

array([1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1])

In [44]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.2493124 , 0.7506876 ],
       [0.78055872, 0.21944128],
       [0.26542573, 0.73457427],
       [0.1409818 , 0.8590182 ],
       [0.56106711, 0.43893289],
       [0.63343525, 0.36656475],
       [0.72231073, 0.27768927],
       [0.16486825, 0.83513175],
       [0.32748514, 0.67251486],
       [0.24247   , 0.75753   ],
       [0.28326379, 0.71673621],
       [0.14711157, 0.85288843],
       [0.26289269, 0.73710731],
       [0.68038546, 0.31961454],
       [0.22415901, 0.77584099],
       [0.87482587, 0.12517413],
       [0.20152826, 0.79847174],
       [0.20041004, 0.79958996],
       [0.75485694, 0.24514306],
       [0.60263752, 0.39736248],
       [0.16966727, 0.83033273],
       [0.25843209, 0.74156791],
       [0.83587525, 0.16412475],
       [0.30553265, 0.69446735],
       [0.29805   , 0.70195   ],
       [0.80070239, 0.19929761],
       [0.69634546, 0.30365454],
       [0.16438053, 0.83561947],
       [0.28675812, 0.71324188],
       [0.83536488, 0.16463512],
       [0.

In [46]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, yhat,pos_label=0)

np.float64(1.0)

In [32]:
df.shape

(303, 14)